# 应用服务 WEB 访问端口
server:
  port: 9001

spring:
  datasource:
    username: root
    password: yc1234
    url: jdbc:mysql://124.222.253.96/reservation?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 124.222.253.96 #ip地址
    port: 6379 #端口号
    password:
    database: 0
    jedis: #连接池
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认为8
        max-wait: -1 #最大阻塞等待时间，负值表示没有限制，默认为-1
        max-idle: 4 #最大控线连接，默认为8
        min-idle: 0 #最小空闲连接，默认为0

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location: classpath:/mybatis/config/mybatis-config.xml
